config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'

  #admin
  namespace :admin do
    resources :customers, only:[:show,:edit,:update, :index]
    resources :orders, only:[:index,:show,:update] do
      member do
        get :current_index
      resource :order_details,only: [:update]
    end
    end
    resources :items, only:[:index,:new,:create,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update]
    resources :orders, only:[:show,:update]
    get '/search' => 'searches#search'

  end

  #public
  scope module: :public do
    resource :customers, only:[:show] do
     collection do
       patch "information/update" => "customers#update", as:"update"
       get "information/edit" => "customers#edit", as:"edit"
       get 'unsubscribe'
       patch 'withdraw'
     end
   end
    resources :orders, only:[:new,:index,:show,:create] do
     collection do
       post 'confirm'
       get 'thanx'
     end
   end
    resources :items, only:[:index,:show] do
      collection do
        get 'genre/:id'=> 'items#genre', as:'genre'
      end
    end
    resources :cart_items, only:[:index,:update,:destroy,:create] do
      collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end
    resources :shipping_addresses, only:[:index,:edit,:create,:update,:destroy]
    get '/search' => 'searches#search'

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :kana_last_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, numericality: true, length: {is: 7}
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :email, presence: true
  

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  def full_name
    self.first_name + " " + self.last_name
  end         

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :email, :postal_code, :address, :phone_number, :is_deleted)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kana_first_name, :kana_last_name, :email, :postal_code, :address, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_path(current_customer)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <h4 class="col-4 bg-light text-center"><%= @customer.full_name %>さんの会員情報編集</h4>
  <div class="row">
    <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
    <table class="table table-borderless">
     <tr>
      <td><%= f.label :id,"会員ID" %></td>
      <td><%= @customer.id %></td>
     </tr>
     <tr>
       <td><%= f.label :"氏名" %></td>
       <td><%= f.text_field :first_name, required: true, class: "form-control" %></td>
       <td><%= f.text_field :last_name, required: true,class: "form-control" %></td>
     </tr>
     <tr>
       <td><%= f.label :"フリガナ" %></td>
       <td><%= f.text_field :kana_first_name,required: true, class: "form-control" %></td>
       <td><%= f.text_field :kana_last_name,required: true, class: "form-control" %></td>
     </tr>
     <tr>
       <td><%= f.label :"郵便番号" %></td>
       <td><%= f.text_field :postal_code,required: true, class: "form-control" %></td>
     </tr>
     <tr>
       <td><%= f.label :"住所" %></td>
       <td><%= f.text_field :address,required: true, class: "form-control" %></td>
     </tr>
     <tr>
       <td><%= f.label :"電話番号" %></td>
       <td><%= f.text_field :phone_number,required: true, class: "form-control" %></td>
     </tr>
     <tr>
       <td><%= f.label :"メールアドレス" %></td>
       <td><%= f.text_field :email,required: true, class: "form-control" %></td>
     </tr>
     <tr>
       <td><%= f.label :"会員ステータス" %></td>
       <td class="form-inline">
          　<%= f.radio_button :is_deleted, false %>
          　<%= f.label :is_deleted, "有効" %>
          　<%= f.radio_button :is_deleted, true %>
          　<%= f.label :is_deleted, "退会" %>
       </td>
     </tr>
     <tr>
      <td></td>
      <td><%= f.submit"変更を保存", class: 'btn btn-success btn-lg' %></td>
     </tr>

    </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <h4 class="col-2 bg-light text-center">会員一覧</h4>
  <div class='row'>
    <div class="col-md-12 px-5 px-sm-0">
   <table class='table border-bottom'>
    <thead class="bg-light">
     <tr>
       <th>会員ID</th>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>ステータス</th>
     </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>

        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to "#{customer.full_name}",admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.active_for_authentication? %>
              <p class="text-success font-weight-bold">有効</p>
            <% else %>
              <p class="text-secondary font-weight-bold">退会</p>
            <% end %>
          </td>
        </tr>
      <% end %>
     </tbody>
   </table>
   </div>
   <div class="mx-auto mb-3">
     <%= paginate @customers %>
   </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
  <h4 class="col-4 bg-light text-center"><%= @customer.full_name %>さんの会員詳細</h4>
  <div class='row'>
   <table class ="table table-borderless">
      <tr>
        <td>会員ID</td><td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td><td><%= @customer.first_name %> <%= @customer.last_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td><td><%= @customer.kana_first_name %> <%= @customer.kana_last_name %></td>
      </tr>
      <tr>
        <td>郵便番号</td><td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td><td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td><td><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td><td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td>
          <% if @customer.active_for_authentication? %>
            <p class="text-success font-weight-bold">有効</p>
          <% else %>
            <p class="text-secondary font-weight-bold">退会</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <%= link_to "編集する",edit_admin_customer_path,class: 'btn btn-success mr-5' %>
          <%= link_to "注文履歴一覧を見る", admin_orders_path,class: "btn btn-primary ml-5" %>
        </td>
      </tr>
    </table>

  </div>
</div>