config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'

  #admin
  namespace :admin do
    resources :customers, only:[:show,:edit,:update, :index]
    resources :orders, only:[:index,:show,:update] do
      member do
        get :current_index
      resource :order_details,only: [:update]
    end
    end
    resources :items, only:[:index,:new,:create,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update]
    resources :orders, only:[:show,:update]
    get '/search' => 'searches#search'

  end

  #public
  scope module: :public do
    resource :customers, only:[:show] do
     collection do
       patch "information/update" => "customers#update", as:"update"
       get "information/edit" => "customers#edit", as:"edit"
       get 'unsubscribe'
       patch 'withdraw'
     end
   end
    resources :orders, only:[:new,:index,:show,:create] do
     collection do
       post 'confirm'
       get 'thanx'
     end
   end
    resources :items, only:[:index,:show] do
      collection do
        get 'genre/:id'=> 'items#genre', as:'genre'
      end
    end
    resources :cart_items, only:[:index,:update,:destroy,:create] do
      collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end
    resources :shipping_addresses, only:[:index,:edit,:create,:update,:destroy]
    get '/search' => 'searches#search'

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

 validates :customer_id, :item_id, :quantity, presence: true
 validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :kana_last_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, numericality: true, length: {is: 7}
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :email, presence: true
  

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  def full_name
    self.first_name + " " + self.last_name
  end         

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :orders, through: :order_details
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :name, length:{maximum:50}, uniqueness: true
  validates :explanation, length:{maximum:200}

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

  validates :customer_id, :address, :name, :postage,
    :total_price, :payment_method,
  presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :postage, :total_price, numericality: { only_integer: true }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer
  
  validates :postal_code, presence: true, numericality: true, length: {is: 7}
  validates :name, presence: true
  validates :address, presence: true

  def order_address
    "〒" + self.postal_code + "   " + self.address+ "   " + self.name
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!


  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @sum = 0
    @subtotals = @order_details.map { |order_details| order_details.taxed_price * order_details.quantity }
    @sum = @subtotals.sum
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    flash[:notice] = "注文ステータスの変更をしました"
    redirect_to admin_order_path(@order)

    if @order.status == "入金確認"
      @order.order_details.each do |order_detail|
        order_detail.update(status: 1)
      end
    end
  end

  def order_params
    params.require(:order).permit(:name,:shipping_cost,:total_price,:payment_method,:status,:address,:postal_code,:making_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_customer!, except: [:top, :about]
  # before_action :configure_permitted_parameters, if: :devise_controller?

  include ApplicationHelper


  private

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order('id DESC').limit(4)
    @genres = Genre.all
  end

  def about
  end


end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_name(customer)
    customer.first_name + customer.last_name
  end

  def full_address(key)
    "#{key.postal_code}#{key.address}"
  end

  def current_cart
    @cart_items = current_customer.cart_items
  end

  def tax_price(price)
    (price * 1.1).floor
  end

  def subtotal(sub)
    (tax_price(sub.item.non_taxed_price) * sub.quantity)
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
    price +=  subtotal(total)
    end
    return price
  end

  def billing(order)
    total_price(current_cart) + order.postage
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
<div class='container'>
<h2>注文履歴一覧</h2>
	<div class="row">
	    <table class="table table-hover table-bordered table-condensed">
	      <thead>
	        <tr class="info">
	        <th class="col-xs-3">購入日時</th>
	        <th>購入者</th>
	        <th class="col-xs-1">注文個数</th>
	        <th class="col-xs-2">注文ステータス</th>
	        </tr>
	      </thead>
	      <tbody>
	        <% @orders.each do |order| %>
	          <tr>
			        <td>
			          <%= link_to admin_order_path(order)  do %>
			            <%= order.created_at.strftime('%Y/%m/%d %H:%M')  %>
			          <% end %>
			        </td>
			        <td class="text-left">
			          <%= full_name(order.customer) %>
			        </td>
			        <td class="text-right">
			          <%= order.order_details.count %>
			        </td>
	    	        <td>
	    	          <%= order.status %>
	     	        </td>
	     	      </tr>
			    <% end %>
			  </tbody>
			</table>
    <div class="mx-auto">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<% provide(:title, "注文詳細") %>
<div class="container px-5 px-sm-0">
  <h2 class="my-5 text-center">注文履歴詳細</h2>
  <div class="row">
    <div class="col-12">
      <table class="table table-borderless">
         <thead>
            <tr><th>購入者</th><td><%= full_name(@order.customer) %></td></tr>
            <tr><th>注文日</th><td><%= @order.created_at.strftime("%Y/%m/%d")%></td></tr>
            <tr><th>配送先</th><td>〒<%= full_address(@order)%>　<%= @order.name %></td></tr>
            <tr><th>支払方法</th><td><%= @order.payment_method %></td></tr>
            <tr>
             <th>注文ステータス</th>
              <td>
                <%= form_with(model: @order, url: admin_order_path, method: :patch, local: true) do |f| %>
                <%= f.select :status, Order.statuses.keys,class:"status"%>
                <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                <% end %>
              </td>
           </tr>
         </thead>
     </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-xs-8">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name%></td>
              <td><%= order_detail.taxed_price.floor.to_s(:delimited) %></td>
              <td><%= order_detail.quantity %></td>
              <td><%= (order_detail.taxed_price * order_detail.quantity.floor).to_s(:delimited) %></td>
              <td>
                <%= form_with(model: order_detail, url: admin_order_details_path(order_detail.id),method: :patch, local: true) do |f|%>
                <%= f.select :status, OrderDetail.statuses.keys, class:"making_status"%>
                <%= f.submit "更新", class:"btn btn-success"%>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="col-xs-3 off-set-1">
      <table class="table">
          <tr>
            <th>送料</th>
            <td class="text-right col-xs-5">¥<%= @order.postage %></td>
          </tr>
          <tr>
            <th>商品合計</th>
            <td class="text-right col-xs-5">¥<%= @sum.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td class="text-right col-xs-5">¥<%= @order.total_price.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th></th>
            <td class="text-right col-xs-5"><%= link_to "注文履歴へ戻る", admin_orders_path, class:"btn btn-outline-secondary"%></td>
          </tr>
      </table>
      </div>
    </div>
  </div>
</div>