config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'

  #admin
  namespace :admin do
    resources :customers, only:[:show,:edit,:update, :index]
    resources :orders, only:[:index,:show,:update] do
      member do
        get :current_index
      resource :order_details,only: [:update]
    end
    end
    resources :items, only:[:index,:new,:create,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update]
    resources :orders, only:[:show,:update]
    get '/search' => 'searches#search'

  end

  #public
  scope module: :public do
    resource :customers, only:[:show] do
     collection do
       patch "information/update" => "customers#update", as:"update"
       get "information/edit" => "customers#edit", as:"edit"
       get 'unsubscribe'
       patch 'withdraw'
     end
   end
    resources :orders, only:[:new,:index,:show,:create] do
     collection do
       post 'confirm'
       get 'thanx'
     end
   end
    resources :items, only:[:index,:show] do
      collection do
        get 'genre/:id'=> 'items#genre', as:'genre'
      end
    end
    resources :cart_items, only:[:index,:update,:destroy,:create] do
      collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end
    resources :shipping_addresses, only:[:index,:edit,:create,:update,:destroy]
    get '/search' => 'searches#search'

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

 validates :customer_id, :item_id, :quantity, presence: true
 validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :kana_last_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, numericality: true, length: {is: 7}
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :email, presence: true
  

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  def full_name
    self.first_name + " " + self.last_name
  end         

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :orders, through: :order_details
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :name, length:{maximum:50}, uniqueness: true
  validates :explanation, length:{maximum:200}

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

  validates :customer_id, :address, :name, :postage,
    :total_price, :payment_method,
  presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :postage, :total_price, numericality: { only_integer: true }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer
  
  validates :postal_code, presence: true, numericality: true, length: {is: 7}
  validates :name, presence: true
  validates :address, presence: true

  def order_address
    "〒" + self.postal_code + "   " + self.address+ "   " + self.name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_customer!, except: [:top, :about]
  # before_action :configure_permitted_parameters, if: :devise_controller?

  include ApplicationHelper


  private

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order('id DESC').limit(4)
    @genres = Genre.all
  end

  def about
  end


end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_name(customer)
    customer.first_name + customer.last_name
  end

  def full_address(key)
    "#{key.postal_code}#{key.address}"
  end

  def current_cart
    @cart_items = current_customer.cart_items
  end

  def tax_price(price)
    (price * 1.1).floor
  end

  def subtotal(sub)
    (tax_price(sub.item.non_taxed_price) * sub.quantity)
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
    price +=  subtotal(total)
    end
    return price
  end

  def billing(order)
    total_price(current_cart) + order.postage
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: obj.errors.count,
                 resource: obj.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9 mx-auto'>
    	  <p>©️CopyRightベンチプレス.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand text-light" href="/"><span>ながのCAKE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-column" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to "商品一覧", admin_items_path, class: 'btn nav-link text-light mr-3' %>
          </li>
          <li>
            <%= link_to "会員一覧", admin_customers_path, class: 'btn nav-link text-light mr-3' %>
          </li>
          <li>
            <%= link_to "注文履歴一覧", admin_orders_path, class: 'btn nav-link text-light mr-3' %>
          </li>
          <li>
            <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn nav-link text-light mr-3' %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'btn nav-link text-light mr-3' %>
          </li>
        <% else %>
          <li>
            <%= link_to "About", about_path, class: 'btn nav-link text-light mr-5' %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class: 'btn nav-link text-light mr-5' %>
          </li>
          <li>
            <%= link_to "新規登録", new_customer_registration_path, class: 'btn nav-link text-light mr-5' %>
          </li>
          <li>
            <%= link_to "ログイン", new_customer_session_path, class: 'btn nav-link text-light' %>
          </li>
        <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <%= render 'admin/searches/form', path: admin_search_path %>
          <% else %>
            <%= render 'public/searches/form', path: search_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCakeEc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/9eb88cfd56.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if customer_signed_in? %>
      <%= render 'layouts/public/header' %>
    <% elsif %>
      <%= render 'layouts/admin/header' %>
    <% else %>
      <%= render 'layouts/public/header' %>
    <% end %>

    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>
  </body>
</html>